### ISSUE TITLE
Body mist main tag

### ISSUE THREAD

**Issue by slimluccii** [smolgeorgie/the-client-website#2]
De body moet een main tag hebben rond je main content

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

https://github.com/smolgeorgie/the-client-website/blob/12862ea185e3f3cd3f3f479dfec8b956cf11367a/index.html#L10

**Comment by smolgeorgie** [comment]
dat is helaas niet gelukt, dat verplaatst mijn css compleet
