### ISSUE TITLE
Article bevat geen tekst of betekenisvolle elementen

### ISSUE THREAD

**Issue by slimluccii** [smolgeorgie/the-client-website#4]
Je moet de article betekenisvol maken in de code. Een svg heeft alleen visuele waarde. Voeg tekst toe aan de article en verberg het visueel.

https://css-tricks.com/inclusively-hidden/

https://github.com/smolgeorgie/the-client-website/blob/12862ea185e3f3cd3f3f479dfec8b956cf11367a/index.html#L19C9-L19C9

**Comment by smolgeorgie** [comment]
is gedaan thanks
